version: '3'

volumes:
  marni_db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/livia/projects/marni-endpoint/docker/db

services:
  db:
    image: mariadb:10.4
    container_name: marni_db
    environment:
      MYSQL_ROOT_PASSWORD: marni
      MYSQL_DATABASE: marni_db
      MYSQL_USER: marni
      MYSQL_PASSWORD: marni
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - "3306:3306"
    volumes:
      - marni_db_vol:/var/lib/mysql
      - ./seed:/seed

  php_admin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: marni_php_admin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

